sudo: false
language: node_js
node_js:
- 10
script:
- npm run update-plugins
- npm test
- npm version patch --no-git-tag-version
deploy:
  - provider: npm
    email: github@stefanbuck.com
    skip-cleanup: true
    api_key:
      secure: nySQRpHqhb4wbhnyVYhFSY/ZfonrNIPzVGcTO6/llXYOtjXLiJUZiECdHNenRTOkgsr7JOfSQbMhU77mBhVCsbM3CwmcJGhslKgng5WJ6uyxGAbF3OrVQ/guLFlQ6tMx2seFInBP4TfJJip8FasqFa6QeaojdQC/nSL+/NR5BrIh8XWNvXamsSAZYrM2smlhKKCqzbWcRJv0JVCJFnYtGd5QQCHN3khw/tTWGO1zQrL+ZFHdy2/ZipCUcJa1Al42htOMF1nYdPzeOEwpNgY9rdBrb2ieJpklRbGerVfXyE/XHHjPLDfuGl7T/9TmZE210XNcaYK7wgyd/gZt7ZlmhEkPnsEXX3JIoYxmJEGJEbTjtc00tamnznssnSfvUs8R0fkggz6M0bTczmNrMBsVGgRBQn32k/3r0JvfR36TqDhkyMUhPaIstdtmvVFoKpK2+kEox1VmTv42n7I4FRtMj7tl56V/g+n8fFoTmffRb7XshKI+W7qT+whl6NqfMPOFsc0aYVMC/3x9Q2dR7J6H76JBl0k0ES5x53QBemrsgzVeaj9QD1kwLPG6smLjgU1rxwwKNXjTbbo8mTfHnVu9RFsDxgsPb8k1fHom83heuWxx/pFWOGsLGTCWm3EeoUg8lzHD/LMUSykto7Igou+ctvhdApHP/fCxVDPHj8mu71M=
  - provider: pages
    target-branch: master
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true